"""empty message

Revision ID: 54704cf1016c
Revises: 6436f02f48b8
Create Date: 2025-03-15 13:36:44.500629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54704cf1016c'
down_revision = '6436f02f48b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
