"""empty message

Revision ID: b30cb41afaed
Revises: f0f550f60bbc
Create Date: 2025-03-06 23:35:09.831185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30cb41afaed'
down_revision = 'f0f550f60bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office', sa.Integer(), nullable=False))
        batch_op.drop_column('offices')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offices', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('office')

    # ### end Alembic commands ###
